# Generated by Django 5.0.6 on 2024-06-16 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
