# Generated by Django 5.0.6 on 2024-05-20 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel_plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='PlanID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_plan.plan'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='PlanID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_plan.plan'),
        ),
        migrations.AddField(
            model_name='review',
            name='PlanID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_plan.plan'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='PlanID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_plan.plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='TGID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_plan.travelgroup'),
        ),
        migrations.AddField(
            model_name='plan',
            name='TSID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_plan.travelstyle'),
        ),
    ]
