# Generated by Django 5.0.6 on 2024-06-16 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_plan', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='Budget',
            new_name='budget',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='EndDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='StartDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='UserID',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='Destination',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='EstimatedCost',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='TGID',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='TSID',
        ),
        migrations.AddField(
            model_name='plan',
            name='destination_city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='destination_country',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='travel_group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='travel_plan.travelgroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='travel_style',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='travel_plan.travelstyle'),
            preserve_default=False,
        ),
    ]
